error.generic.message=an unexpected error occured
test01.description=Verify that no log entries were forged, deleted or added
test01.nok.message=log entry and attributes of the first entry where the HMAC chain does not verify
test01.file.not.found.message=secure Log file not provided
test02.description=Verify the signature in the checkpoint entries of the secure logs
test02.nok.message=checkpoint entry and attributes of the entry : {0}, {1} the signature does not verify
test02.file.not.found.message=secure Log file not provided
test03.description=Verify the number of generated voting card in the control components
test03.nok.message=checkpoint entry and attributes of the first entry where the signature does not verify
test03.file.not.found.message={0} not provided
test04.description=Verify that the secure logs of the control components contain the same number of votes than the ballot box
test04.nok.message=checkpoint entry and attributes of the first entry where the signature does not verify
test04.file.not.found.message={0} not provided
test05.description=Verify that the encrypted votes in the secure log are equal to the encrypted votes in the ballot box
test05.nok.message=checkpoint entry and attributes of the entry : {0}, {1} the signature does not verify
test05.nok.numberVotes.mismatch.message=the number of encrypted votes in the secure logs and downloadboxes are not equal
test05.file.not.found.message={0} not provided
test06.description=Verify that there is no more than one vote per voter processed by the CCRs
test06.nok.message=Voting Card Id {0} contain multiple votes in the secure logs
test06.file.not.found.message={0} not provided
test07.description=Verify that the control components processed maximum 5 confirmation attempts per voting card
test07.nok.message=Voting Card Ids {0} contain multiple votes in the secure logs
test07.file.not.found.message={0} not provided
