error.generic.message=an unexpected error occured
verification01.description=Verify that no log entries were forged, deleted or added
verification01.nok.message=Log entry and attributes of the first entry where the HMAC chain does not verify [{0}] [{1}]
verification01.file.not.found.message=secure Log file not provided
verification02.description=Verify the signature in the checkpoint entries of the secure logs
verification02.nok.message=Checkpoint entry and attributes of the entry \: {0} the signature does not verify
verification02.file.not.found.message=secure Log file not provided
verification03.description=Verify the number of generated voting card in the control components
verification03.nok.logs.mismatch.voters.message=The number of log entries [{0}] does not match with the number of voters [{1}]
verification03.nok.no.value.message=No value found while counting log foreach control component
verification03.nok.count.control.component.message=Count of log for partial choice code generation is not the same for each control component
verification03.nok.number.control.component.message=Number of control component is not 4 [{0}]
verification03.nok.no.genpcc.log.found.message=No GENPCC log found for the defined electionEventId [{0}]
verification03.file.not.found.message={0} not provided
verification04.description=Verify that the secure logs of the control components contain the same number of votes than the ballot box
verification04.nok.no.value.message=No value found while counting log foreach control component
verification04.nok.number.control.component.message=Number of control component is not 4 [{0}]
verification04.nok.no.genpvccc.log.found.message=No GENPVCC log found for the defined electionEventId [{0}]
verification04.nok.count.control.component.message=Count of log for partial vote cast code generation is not the same for each control component
verification04.nok.logs.mismatch.voters.message=The number of log entries [{0}] does not match with the number of voters [{1}]
verification04.file.not.found.message={0} not provided
verification05.description=Verify that the encrypted votes in the secure log are equal to the encrypted votes in the ballot box
verification05.nok.message=checkpoint entry and attributes of the entry \: {0}, {1} the signature does not verify
verification05.nok.duplicate.message=Duplicate votingCardId in downloadedBallotBox files
verification05.nok.numberVotes.mismatch.message=the number of encrypted votes in the secure logs and downloadboxes are not equal
verification05.nok.encryptedOptions.mismatch.message=EncryptedOptions is not the same in DownloadedBallotBox and SecureLogs [{0}] [{1}]
verification05.nok.unknow.votingCardId.message=Unknown votingCardId [{0}]
verification05.file.not.found.message={0} not provided
verification06.description=Verify that there is no more than one vote per voter processed by the CCRs
verification06.nok.message=Voting Card Id {0} contain multiple votes in the secure logs
verification06.file.not.found.message={0} not provided
verification07.description=Verify that the control components processed maximum 5 confirmation attempts per voting card
verification07.nok.message=Voting Card Ids {0} contain multiple votes in the secure logs
verification07.file.not.found.message={0} not provided
verification08.description=Verify that the votes containing vote cast codes in the ballot box are in the list of successful votes
verification08.nok.message=there is a mismatch between the list of successful votes and the download ballot box
verification08.file.not.found.message={0} not provided
