error.generic.message=an unexpected error occured
verification71.description=Verify the signature of the successful votes.
verification71.nok.message=The signature verification of the file [{0}] failed
verification72.description=Verify the signature of the failed votes.
verification72.nok.message=The signature verification of the file [{0}] failed
verification73.description=Verify the signature of ballot box votes.
verification73.nok.message=The signature verification of the vote of ballot failed