error.generic.message=an unexpected error occured
test01.description=Check that p is prime
test01.nok.message=p is not prime
test01.file.not.found.message=encryptionParameters.json is missing
test02.description=Check that q is prime
test02.nok.message=q is not prime
test02.file.not.found.message=encryptionParameters.json is missing
test03.description=Check that p is 2q + 1
test03.nok.message=p is not a strong prime
test03.file.not.found.message=encryptionParameters.json is missing
test04.description=Check that bitlength(p) >\= 2048
test04.nok.message=p is not prime
test04.file.not.found.message=encryptionParameters.json is missing
test05.description=Check that the voting options [vo] are prime
test05.nok.message={0} is not prime
test05.file.not.found.message=dataConfig_[EE].json is missing
test06.description=Check that the voting options are quadratic residues of the group
test06.nok.message=Euler criterion does not equal to 1 for {0}
test06.file.not.found.message=input file is missing
test07.description=Check that components of the public key of the electoral authorities are part of the group q
test07.nok.message=Euler criterion does not equal to 1 for {0}
test07.file.not.found.message=electoralAuthority.json is missing
test08.description=Check that the commitment parameters are part of the group
test08.nok.message=Euler criterion does not equal to 1 for {0}
test08.file.not.found.message=commitmentParameters.json is missing
test09.description=Check that the number of primer numbers corresponds to the number of voting options and there are no prime numbers repeated
test09.nok.message.alias.vote.nok=alias {0} does not correspond to voteIdentification in the configuration-anonymized.xml
test09.nok.message.prime.number.mutually.distinct.nok=the prime number fields \: {0} are not mutually distinct
test09.nok.message.number.of.prime.number.and.answer.nok=The number of prime numbers does not correspond to the number of answerElements in the configuration-anonymized.xml
test09.nok.message.alias.election.nok=alias {0} does not correspond to electionIdentification in the configuration-anonymized.xml
test09.nok.message.number.of.distinct.prime.number.and.lists.nok=The number of distinct prime numbers does not correspond to the number of list elements in the configuration-anonymized.xml, The following prime numbers are repeated\: {0}
test09.nok.message=The following prime numbers are repeated\: {0}
test09.nok.message.number.of.candidate.prime.number.and.vo.nok=The number of candidate prime numbers does not correspond to the expected number of voting options for candidates. {0} and {1}
test09.file.not.found.message=dataConfig_[EE].json is missing is missing
test10.description=Checks that the generator g is 2
test10.nok.message=g does not equal 2
test10.file.not.found.message=encryptionParameters.json is missing
test31.description=Check that the number of credentials corresponds to the number of voters in the electoral roll
test31.nok.message=The number of credentials and the number of expected voters do not match\: There are {0} credentials, but {1} voters
test31.file.not.found.message=credentialsData.csv is missing
test71.description=Verify the signature of the eCH-0045 file
test71.nok.message=The signature verification of the file {0} failed
test71.file.not.found.message=file [{0}] is missing
test72.description=Verify the signature of the eCH-0157 or eCH-0159
test72.nok.message=The signature verification of the file {0} failed
test72.file.not.found.message=file [{0}] is missing
test73.description=Verify the signature of the configuration-anonymized.xml
test73.nok.message=The signature verification of the file {0} failed
test73.file.not.found.message=file [{0}] is missing
test74.description=Verify the signature of the dataConfig_updated.json
test74.nok.message=The signature verification of the file dataConfig_updated failed
test74.file.not.found.message=file [{0}] is missing
test75.description=Verify the signature of the AP_election_import_[EE_alias].json
test75.nok.message=The signature verification of the file AP_election_import_[EE_ID].json failed
test75.file.not.found.message=file [{0}] is missing