## Hereafter you can override any property of the Swiss Post Verifier backend.

direct.trust.keystore.location=./direct-trust/public_keys_keystore_verifier.jks
direct.trust.keystore.password.location=./direct-trust/public_keys_keystore_verifier_pw.txt
