## Hereafter you can override any property of the Swiss Post Verifier backend.

direct.trust.keystore.location=./direct-trust/public_keys_keystore_verifier.p12
direct.trust.keystore.password.location=./direct-trust/public_keys_keystore_verifier_pw.txt

# Defines the password used for the decryption of the verifiable dataset. Default is empty. Must be set and respect the following:
# - the size of the password is equal to or greater than 24.
# - the size of the password is equal to or smaller than 64.
# - the password contains at least one upper case letter.
# - the password contains at least one lower case letter.
# - the password contains at least one special character.
# - the password contains at least one digit.
#import.zip.decryption.password=