error.generic.message=an unexpected error occured
test01.description=Verify that the prime numbers were mapped to the correct answers / candidates / lists in evoting-decrypt.xml
test01.nok.message=The occurences for option {0} are different in decryptedBallots.csv and evoting-decrypt.csv
test01.file.not.found.message=encryptionParameters.json is missing
test02.description=Verify that the number of yes / no / blank votes in the eCH-0110 matches the information in evoting-decrypt.xml
test02.nok.message=The count of the answer {1} of the question {0} does not match
test02.file.not.found.message=encryptionParameters.json is missing
test03.description=Verify that the number of candidate votes in the eCH-0110 corresponds to the information in the evoting-decrypt.xml (applies to both proportional and majority elections)
test03.nok.message=The count for the candidate {0} does not match
test03.file.not.found.message=encryptionParameters.json is missing
test04.description=Verify that the number of votes for a list in the eCH-0110 corresponds the information in the eCH-0110 (applies only to proportional elections)
test04.nok.message=The occurrences for list {1} are different for counting Circle {0} in eCH-0110 and evoting-decrypt
test04.file.not.found.message=encryptionParameters.json is missing
test71.description=Check signature of decompressedVotes.csv
test71.nok.message=The signature verification of the decompressedVotes.csv failed
test71.file.not.found.message=file [{0}] is missing
test72.description=Check signature of evoting-decrypt.xml
test72.nok.message=test72 not ok
test72.file.not.found.message=file [{0}] is missing
test73.description=Check signature of eCH-0110.xml
test73.nok.message=test73 not ok
test73.file.not.found.message=file [{0}] is missing
test74.description=Check Signature of the eCH-0110 PDF report
test74.nok.message=test74 not ok
test74.file.not.found.message=file [{0}] is missing
test75.description=Check signature of the bulletin par bulletin PDF report
test75.nok.message=test75 not ok
test75.file.not.found.message=file [{0}] is missing
