error.generic.message=an unexpected error occured
test01.description=Verify that the prime numbers were mapped to the correct answers / candidates / lists in evoting-decrypt.xml
test01.nok.message=The occurences for option {0} are different in decryptedBallots.csv and evoting-decrypt.csv
test01.file.not.found.message=encryptionParameters.json is missing
test02.description=Verify that the number of yes / no / blank votes in the eCH-0110 matches the information in evoting-decrypt.xml
test02.nok.message=The count of the answer {1} of the question {0} does not match
test02.file.not.found.message=encryptionParameters.json is missing
test03.description=Verify that the number of candidate votes in the eCH-0110 corresponds to the information in the evoting-decrypt.xml (applies to both proportional and majority elections)
test03.nok.message=p is not a strong prime
test03.file.not.found.message=encryptionParameters.json is missing
test04.description=Verify that the number of votes for a list in the eCH-0110 corresponds the information in the eCH-0110 (applies only to proportional elections)
test04.nok.message=p is not prime
test04.file.not.found.message=encryptionParameters.json is missing
test05.description=Verify that the number of valid votes (after cleansing) corresponds to the number of votes in evotingdecrypt. xml
test05.nok.message={0} is not prime
test05.file.not.found.message=dataConfig_[EE].json is missing
test06.description=Verify that no votes were discarded during the decryption process
test06.nok.message=Euler criterion does not equal to 1 for {0}
test06.file.not.found.message=input file is missing

