/*
 * Copyright 2021 Post CH Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ch.post.it.evoting.verifier.common.block.tools.path;

public enum StructureKey {

	CONFIG_ANONYMIZED,
	CREDENTIAL_DATA,
	VOTER_INFORMATION,
	DATA_CONFIG_UPDATED,
	ECH015X,
	ECH0045,
	AP_ELECTION_IMPORT,
	ELECTION_INFORMATION_CONTENTS,
	FAILED_VOTES,
	SUCCESSFUL_VOTES,
	SECURE_LOGS_DIR,
	SECURE_LOG_DIR,
	LOGS_DIR,
	LOGS_CG_DIR,
	CG_SECURE_LOG,
	LOGS_CV_DIR,
	CV_SECURE_LOG,
	MAPPING_CC_HOSTS,
	SECURE_LOG,

	CERTIFICATES_DIR,
	ADMIN_BOARD_DIR,
	ADMIN_BOARD_CERT,
	PLATFORM_ROOT_CA,
	INTEGRATION,
	CA2,
	CA1,
	INTEGRATION_CA,
	ROOT_CA,
	TENANT_100,
	CC_CA_KEYS_DIR,
	CC_CA,

	CRYPTO_SETUP_DIR,
	ELECTORAL_AUTHORITY_PUBLIC_KEY,
	ELECTORAL_PUBLIC_KEY,
	ENCRYPTION_PARAMETERS,
	PRIMES,

	ELECTION_SETUP_DIR,
	VERIFICATION_CARD_SET_DIR,
	VERIFICATION_CARD_SET_ID_DIR,
	VOTING_CARD_SETS_DIR,
	VOTING_CARD_SETS_ID_DIR,
	CONTROL_COMPONENT_CONTRIBUTION,
	RETURN_CODE_GENERATION_REQUEST_PAYLOAD,
	CODES_MAPPING_TABLES_CONTEXT_DATA,
	BALLOT_BOX,

	LOG,

	BALLOT_BOXES_DIR,
	BALLOT_BOX_ID_DIR,
	BALLOT_BOX_OFFLINE_DIR,
	COMMITMENT_PARAMETERS,
	DECOMPRESSED_VOTES,
	ENCRYPTED_BALLOTS,
	PROOFS,
	REENCRYPTED_BALLOTS,
	BALLOT_BOX_INITIAL,
	BALLOT_BOX_ONLINE_MIXING,
	BALLOT_BOX_OFFLINE_MIXING,
	DOWNLOADED_BALLOT_BOX,

	CC_MIXING_KEYS_DIR,
	CC_MIXING_KEYS,

	RESULTS_DIR,
	ECH0110,
	EVOTING_DECRYPT_RESULT,
	INVALID_VOTES_RESULT,
	INVALID_VOTES_DECRYPT_RESULT,
	VALID_VOTES_RESULT
}
