package ch.post.it.evoting.verifier.common.block.tools.path;

public enum StructureKey {

    CONFIG_ANONYMIZED,
    CREDENTIAL_DATA,
    VOTER_INFORMATION,
    DATA_CONFIG_UPDATED,
    ECH015X,
    ECH0045,
    AP_ELECTION_IMPORT,
    ELECTION_INFORMATION_CONTENTS,

    CERTIFICATES_DIR,
    ADMIN_BOARD_DIR,
    ADMIN_BOARD_CERT,
    PLATFORM_ROOT_CA,
    INTEGRATION_CA,
    TENANT_100,

    CRYPTO_SETUP_DIR,
    DECRYPTION_KEY,
    ELECTORAL_AUTHORITY,
    ENCRYPTION_PARAMETERS,

    ELECTION_SETUP_DIR,
    VERIFICATION_CARD_SET_DIR,
    VERIFICATION_CARD_SET_ID_DIR,
    VOTING_CARD_SETS_DIR,
    VOTING_CARD_SETS_ID_DIR,
    CODES_MAPPING_TABLES_CONTEXT_DATA,
    BALLOT_BOX,

    LOG,

    BALLOT_BOXES_DIR,
    BALLOT_BOX_ID_DIR,
    BALLOT_BOX_OFFLINE_DIR,
    COMMITMENT_PARAMETERS,
    DECOMPRESSED_VOTES,
    ENCRYPTED_BALLOTS,
    PROOFS,
    REENCRYPTED_BALLOTS,
    BALLOT_BOX_ONLINE_MIXING,
    DOWNLOADED_BALLOT_BOX,

    CC_MIXING_KEYS_DIR,
    CC_MIXING_KEYS

}
