server.address=127.0.0.1
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=k.H5{6XPpvf%X<Kq
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=verifier-backend