server.address=127.0.0.1
server.port=8080
# Enable/disable the scanning of blocks. If property missing, @ConditionalOnProperty does not match.
block1.enabled=true
block2.enabled=true
block3.enabled=true
block4.enabled=true
