verifier.blocks=ch.post.it.evoting.verifier.block.block1.Block1TestSuite;\
ch.post.it.evoting.verifier.block.block4.Block4TestSuite;\
ch.post.it.evoting.verifier.block.block3.Block3TestSuite;\
ch.post.it.evoting.verifier.block.block2.Block2TestSuite;\

inputDirectory=C:/demo/dataset/input

client.username=
client.password=
#client.username=verifier-frontend
#client.password=$2a$12$WWkKRR8JJXWbNAr84tjAquWKmM9.Zez7/pRl6f4fYzXI2ror4dRSC
#=== TO_BE_DEFINED