verifier.blocks=ch.post.it.evoting.verifier.block.block1.Block1TestSuite;\
ch.post.it.evoting.verifier.block.block4.Block4TestSuite;\
ch.post.it.evoting.verifier.block.block3.Block3TestSuite;\
ch.post.it.evoting.verifier.block.block2.Block2TestSuite;\

inputDirectory=