verifier.blocks=ch.post.it.evoting.verifier.block.block1.Block1VerificationSuite;\
ch.post.it.evoting.verifier.block.block4.Block4VerificationSuite;\
ch.post.it.evoting.verifier.block.block3.Block3VerificationSuite;\
ch.post.it.evoting.verifier.block.block2.Block2VerificationSuite;\

inputDirectory=
