/**
 * @author afries 3/3/2015
 *
 * Copyright (C) 2017 Scytl Secure Electronic Voting SA
 * All rights reserved.
 */
package com.scytl.products.ov.mixnet.commons.ballots;

import com.scytl.products.ov.mixnet.commons.homomorphic.impl.GjosteenElGamalCiphertext;
import com.scytl.products.ov.mixnet.commons.mathematical.impl.ZpElement;

import java.util.List;

/**
 * Represents a ballot that has been encrypted using the ElGamal cryptosystem. An ElGamalEncryptedBallot (like a
 * ciphertext generated by ElGamal cryptosystem), contains the following parts:
 * <ul>
 * <li>A gamma.</li>
 * <li>A list of phi values.</li>
 * </ul>
 * The gamma and phis must be members of the group over which the cryptosystem is operating.
 */
public final class ElGamalEncryptedBallot extends GjosteenElGamalCiphertext implements EncryptedBallot {

    public ElGamalEncryptedBallot(final ZpElement[] parts) {
        super(parts);
    }

    public ElGamalEncryptedBallot(final ZpElement gamma, final List<ZpElement> phis) {
        super(gamma, phis);
    }

    /**
     * Create an ElGamalEncryptedBallot from the received list of {@link ZpElement}. The element in the first
     * position in the list (the element at index zero) will be set as gamma, and all of the remaining elements will be
     * set as phi values.
     *
     * @param elements
     *            a list of group elements, containing a gamma and at least one phi value.
     * @throws IllegalArgumentException
     *             if {@code elements} is null or contains less than two elements.
     */
    // TODO I don't see the benefits of this constructor, only risks
    public ElGamalEncryptedBallot(final List<ZpElement> elements) {
        super(elements);
    }

}
