verifier.blocks=ch.post.it.evoting.verifier.block.block1.Block1TestSuite;\
ch.post.it.evoting.verifier.block.block4.Block4TestSuite;\
ch.post.it.evoting.verifier.block.block3.Block3TestSuite;\
ch.post.it.evoting.verifier.block.block2.Block2TestSuite;\

inputDirectory=
#C:/work/projects/verifier/dataset/input6

client.username=
client.password=
#client.username=verifier-frontend
#client.password=TO_BE_DEFINED