#
# ------------------------------------------------------------------------------------------------
# Copyright 2014 by Swiss Post, Information Technology Services
# ------------------------------------------------------------------------------------------------
# $Id$
# ------------------------------------------------------------------------------------------------
#

test1.description=Test 1
test1.errorMessage.generic=Ce test est en echec pour montrer le résultat
test01isprimep.description=Check that p is prime
