error.generic.message=an unexpected error occured
test01.description=Check that p is prime
test01.nok.message=p is not prime
test01.file.not.found.message=encryptionParameters.json is missing
test02.description=Check that q is prime
test02.nok.message=q is not prime
test02.file.not.found.message=encryptionParameters.json is missing
test03.description=Check that p is 2q + 1
test03.nok.message=p is not a strong prime
test03.file.not.found.message=encryptionParameters.json is missing
test04.description=Check that bitlength(p) >= 2048
test04.nok.message=p is not prime
test04.file.not.found.message=encryptionParameters.json is missing
test05.description=Check that the voting options [vo] are prime
test05.nok.message=[List of numbers where primality test failed] is not prime
test05.file.not.found.message=dataConfig_[EE].json is missing
