test1.errorMessage.generic=Ce test est en echec pour montrer le résultat
test01.description=Check that p is prime
test01.nok.message=p is not prime
test01.file.not.found.message=encryptionParameters.json is missing
