error.generic.message=an unexpected error occurred
verification02.description=Verify online decryption proofs
verification02.failure=The provided decryption proofs are invalid
verification01.description=Verify online shuffle roofs
verification01.nok.message=The shuffle proofs are invalid
