error.generic.message=an unexpected error occured
test01.description=Verify the shuffle argument
test02.description=Verify the product argument
test03.description=Verify the hadamard argument
test04.description=Verify the zero argument
test05.description=Verify the single-value product argument
test06.description=Verify the multi-exponentation argument
test07.description=Verify the decryption proof
test07.nok.message=decryption proof of {0} does not verify
test07.file.not.found.message=file [{0}] is missing
test08.description=Check that the commitment parameters are part of the group
test08.nok.message=Euler criterion does not equal to 1 for elements {0}
test08.file.not.found.message=file commitmentParameters.json is missing
test11.description=Check that the ciphertexts of the offline control component are consistent with the online control component
test11.nok.message=Not ok, the ciphertexts of the offline control component aren't consistent with the online control component
test11.file.not.found.message=file [{0}] is missing
test12.description=Verify that all decrypted votes were correctly factorized into the voting options
test12.nok.message=factorization is not correct for the votes {0}
test12.file.not.found.message=file [{0}] is missing
test21.description=Verify the shuffle argument of the online control components
test21.nok.message=shuffle argument does not verify
test21.file.not.found.message=file [{0}] is missing
test22.description=Verify the product argument of the online control components
test22.nok.message=product argument does not verify
test22.file.not.found.message=file [{0}] is missing
test23.description=Verify the hadamard argument of the online control components
test23.nok.message=hadamard argument does not verify
test23.file.not.found.message=file [{0}] is missing
test24.description=Verify the zero argument of the online control components
test24.nok.message=zero argument does not verify
test24.file.not.found.message=file [{0}] is missing
test25.description=Verify the single-value product argument of the online control components
test25.nok.message=single value argument does not verify
test25.file.not.found.message=file [{0}] is missing
test26.description=Verify the multi-exponentiation argument of the online control components
test26.nok.message=multi exponentiation argument does not verify
test26.file.not.found.message=file [{0}] is missing
test27.description=Verify the decryption proof of the online control components
test27.nok.message=decryption proofs do not verify
test27.file.not.found.message=file [{0}] is missing
test28.description=Check that the commitment parameters are part of the group of the online control components
test28.nok.message=Euler\u0092s criterion does not equal to 1 for these elements [{0}]
test28.file.not.found.message=file [{0}] is missing
test31.description=Check that the ciphertexts of the online control component are consistent
test31.nok.message=Not ok, the ciphertexts of the online control component aren't consistent
test31.file.not.found.message=file [{0}] is missing
test71.description=Verify the signature of the proofs.json
test71.nok.message=The signature verification of the proofs.json failed
test71.file.not.found.message=file [{0}] is missing
test72.description=Verify the signature of reencryptedBallots.csv
test72.nok.message=The signature verification of the evoting-decrypt.xml failed
test72.file.not.found.message=file [{0}] is missing
test73.description=Verify the signature of encryptedBallots.csv
test73.nok.message=test73 not ok
test73.file.not.found.message=file [{0}] is missing
test74.description=Verify the signature of commitmentParameters.json
test74.nok.message=test74 not ok
test74.file.not.found.message=file [{0}] is missing
test75.description=Verify the signature of the online control component proofs
test75.nok.message=test75 not ok
test75.file.not.found.message=file [{0}] is missing