error.generic.message=an unexpected error occurred
verification01.description=Verify the shuffle argument
verification02.description=Verify the product argument
verification03.description=Verify the hadamard argument
verification04.description=Verify the zero argument
verification05.description=Verify the single-value product argument
verification06.description=Verify the multi-exponentation argument
verification07.description=Verify the decryption proof
verification07.nok.message=decryption proof of {0} does not verify
verification07.file.not.found.message=file [{0}] is missing
verification08.description=Check that the commitment parameters are part of the group
verification08.nok.message=Euler criterion does not equal to 1 for elements {0}
verification08.file.not.found.message=file commitmentParameters.json is missing
verification09.description=Check the independence of the commitment generators
verification09.nok.message=test 9 not ok
verification09.file.not.found.message=file commitmentParameters.json is missing
verification11.description=Check that the ciphertexts of the offline control component are consistent with the online control component
verification11.nok.message=Not ok, the ciphertexts of the offline control component aren't consistent with the online control component
verification11.file.not.found.message=file [{0}] is missing
verification12.description=Verify that all decrypted votes were correctly factorized into the voting options
verification12.nok.message=factorization is not correct for the votes {0}
verification12.file.not.found.message=file [{0}] is missing
verification21.description=Verify the shuffle argument of the online control components
verification21.nok.message=shuffle argument does not verify
verification21.file.not.found.message=file [{0}] is missing
verification22.description=Verify the product argument of the online control components
verification22.nok.message=product argument does not verify
verification22.file.not.found.message=file [{0}] is missing
verification23.description=Verify the hadamard argument of the online control components
verification23.nok.message=hadamard argument does not verify
verification23.file.not.found.message=file [{0}] is missing
verification24.description=Verify the zero argument of the online control components
verification24.nok.message=zero argument does not verify
verification24.file.not.found.message=file [{0}] is missing
verification25.description=Verify the single-value product argument of the online control components
verification25.nok.message=single value argument does not verify
verification25.file.not.found.message=file [{0}] is missing
verification26.description=Verify the multi-exponentiation argument of the online control components
verification26.nok.message=multi exponentiation argument does not verify
verification26.file.not.found.message=file [{0}] is missing
verification27.description=Verify the decryption proof of the online control components
verification27.nok.message=decryption proofs do not verify
verification27.file.not.found.message=file [{0}] is missing
verification28.description=Check that the commitment parameters are part of the group of the online control components
verification28.nok.message=Euler\u0092s criterion does not equal to 1 for these elements [{0}]
verification28.file.not.found.message=file [{0}] is missing
verification29.description=Check the independence of the commitment generators of the online control components
verification29.nok.message=test 29 not ok
verification29.file.not.found.message=file commitmentParameters.json is missing
verification31.description=Check that the ciphertexts of the online control component are consistent
verification31.nok.message=Not ok, the ciphertexts of the online control component aren't consistent
verification31.file.not.found.message=file [{0}] is missing
verification71.description=Verify the signature of the proofs.json
verification71.nok.message=The signature verification of the proofs.json failed
verification71.file.not.found.message=file [{0}] is missing
verification72.description=Verify the signature of reencryptedBallots.csv
verification72.nok.message=The signature verification of the evoting-decrypt.xml failed
verification72.file.not.found.message=file [{0}] is missing
verification73.description=Verify the signature of encryptedBallots.csv
verification73.nok.message=test73 not ok
verification73.file.not.found.message=file [{0}] is missing
verification74.description=Verify the signature of commitmentParameters.json
verification74.nok.message=test74 not ok
verification74.file.not.found.message=file [{0}] is missing
verification75.description=Verify the signature of the online control component proofs
verification75.nok.message=The signature verification of the file [{0}] failed
verification75.ccnumber.nok.message=The number of control components in not correct
verification75.file.not.found.message=file [{0}] is missing
