#
# (c) Copyright 2024 Swiss Post Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
server:
  address: 127.0.0.1
  port: 8080

direct:
  trust:
    keystore:
      location: # mandatory
      password:
        location: # mandatory
      type: PKCS12

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  main:
    banner-mode: LOG
  output:
    ansi:
      enabled: always

logging:
  file:
    name: ../logs/verifier-backend.log
  logback:
    rollingpolicy:
      max-history: 0
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log

# Defines the password used for the decryption of the verifiable dataset. Default is empty. Must be set and respect the following:
# - the size of the password is equal to or greater than 24.
# - the size of the password is equal to or smaller than 64.
# - the password contains at least one upper case letter.
# - the password contains at least one lower case letter.
# - the password contains at least one special character.
# - the password contains at least one digit.
import:
  zip:
    decryption:
      password: # mandatory

# Location where to save the unzipped, unencrypted dataset. Default is the location of the "java.io.tmpdir" property. If set, the directory must exist.
#dataset:
#  unzip:
#    location: # optional