server.address=127.0.0.1
server.port=8080
# Enable/disable the scanning of blocks. If property missing, @ConditionalOnProperty does not match.
setup.verification.enabled=true
tally.verification.enabled=true
direct.trust.keystore.location=
direct.trust.keystore.password.location=
direct.trust.keystore.type=JKS

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
