server.address=127.0.0.1
server.port=8080
direct.trust.keystore.location=
direct.trust.keystore.password.location=
direct.trust.keystore.type=PKCS12
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
spring.main.banner-mode=LOG

# Logging
spring.output.ansi.enabled=always
logging.file.name=../logs/verifier-backend.log
logging.logback.rollingpolicy.max-history=0
logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i.log

# Defines the password used for the decryption of the verifiable dataset. Default is empty. Must be set and respect the following:
# - the size of the password is equal to or greater than 24.
# - the size of the password is equal to or smaller than 64.
# - the password contains at least one upper case letter.
# - the password contains at least one lower case letter.
# - the password contains at least one special character.
# - the password contains at least one digit.
import.zip.decryption.password=
