server.address=127.0.0.1
server.port=8080
direct.trust.keystore.location=
direct.trust.keystore.password.location=
direct.trust.keystore.type=PKCS12
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
