verifier.blocks=ch.post.it.evoting.verifier.block.block1.Block1TestSuite;\
  ch.post.it.evoting.verifier.block.block4.Block4TestSuite;
inputDirectory=C:/work/projects/verifier/dataset

client.username=
client.password=
#client.username=verifier-frontend
#client.password=TO_BE_DEFINED