verifier.blocks=ch.post.it.evoting.verifier.block.block1.Block1TestSuite;\
  ch.post.it.evoting.verifier.block.block4.Block4TestSuite;
#  ch.post.it.evoting.verifier.block.block3.Block3TestSuite;
inputDirectory=C:/work/projects/verifier/dataset/input4
outputDirectory=C:/work/projects/verifier/dataset/output
jsonReportName=resultat.json

client.username=
client.password=
#client.username=verifier-frontend
#client.password=TO_BE_DEFINED